"""update_attendance_status_enum

Revision ID: d22a3dbf8bd0
Revises: 5438045b1ef1
Create Date: 2025-12-01 16:22:18.408146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd22a3dbf8bd0'
down_revision: Union[str, Sequence[str], None] = '5438045b1ef1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE attendancestatus ADD VALUE IF NOT EXISTS 'indi'")
    op.execute("ALTER TYPE attendancestatus ADD VALUE IF NOT EXISTS 'bindi'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
